'use client';

import { useState } from 'react';
import { Sparkles, RefreshCw, Download, CheckCircle, AlertTriangle, Loader2, FileText, ArrowRight } from 'lucide-react';
import { useAuth } from '@/components/providers/auth-provider';
import { useResumes } from '@/hooks/api/resume';
import { useJobs } from '@/hooks/api/job';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

interface ResumeChange {
  original: string;
  optimized: string;
  reason: string;
  ats_improvement: string;
  recruiter_impact?: string;
}

interface SkillsOptimization {
  original_order: string[];
  optimized_order: string[];
  reasoning: string;
}

interface KeywordAddition {
  keyword: string;
  where_added: string;
  reason: string;
}

interface OptimizationResult {
  id: string;
  optimized_summary: string;
  optimized_experience: ResumeChange[];
  optimized_skills: SkillsOptimization;
  optimized_projects: ResumeChange[];
  keyword_additions: KeywordAddition[];
  optimization_score: number;
  estimated_ats_improvement: number;
  estimated_match_increase: number;
  estimated_interview_probability: number;
}

function ScoreRing({ value, label, color }: { value: number; label: string; color: string }) {
  return (
    <div className="flex flex-col items-center justify-center bg-card border rounded-xl p-5 text-center">
      <p className={`text-3xl font-bold ${color}`}>{value}</p>
      <p className="text-xs text-muted-foreground mt-1">{label}</p>
    </div>
  );
}

export default function ResumeOptimizerPage() {
  const { user } = useAuth();
  const { data: resumes = [] } = useResumes(user?.id ?? '');
  const { data: jobs = [] } = useJobs();

  const [selectedResumeId, setSelectedResumeId] = useState('');
  const [selectedJobId, setSelectedJobId] = useState('');
  const [optimizing, setOptimizing] = useState(false);
  const [result, setResult] = useState<OptimizationResult | null>(null);
  const [error, setError] = useState('');
  const [downloading, setDownloading] = useState(false);

  const selectedResume = resumes.find((r) => r.id === selectedResumeId);
  const selectedJob = jobs.find((j) => j.id === selectedJobId);

  const handleOptimize = async () => {
    if (!selectedResumeId) { setError('Select a resume.'); return; }
    if (!selectedJobId) { setError('Select a job to optimize for.'); return; }
    setError('');
    setOptimizing(true);
    setResult(null);

    try {
      const token = localStorage.getItem('careeros_token');
      const res = await fetch(`${API_BASE}/api/v1/accelerator/optimize/resume`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ resume_id: selectedResumeId, job_id: selectedJobId }),
      });

      if (res.ok) {
        const data = await res.json() as OptimizationResult;
        setResult(data);
      } else {
        const err = await res.json().catch(() => ({})) as { detail?: string };
        throw new Error(err.detail || 'Optimization failed');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Optimization failed. Please try again.');
    } finally {
      setOptimizing(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    setDownloading(true);
    try {
      const lines: string[] = [];
      const jobLabel = `${selectedJob?.title ?? 'Job'} at ${selectedJob?.company_name ?? ''}`;
      
      lines.push('OPTIMIZED RESUME');
      lines.push(`Optimized for: ${jobLabel}`);
      lines.push(`Original file: ${selectedResume?.original_filename ?? ''}`);
      lines.push(`Generated by CareerOS — ${new Date().toLocaleDateString()}`);
      lines.push('='.repeat(60));
      lines.push('');

      if (result.optimized_summary) {
        lines.push('PROFESSIONAL SUMMARY');
        lines.push('-'.repeat(40));
        lines.push(result.optimized_summary);
        lines.push('');
      }

      if (result.optimized_experience?.length > 0) {
        lines.push('EXPERIENCE IMPROVEMENTS');
        lines.push('-'.repeat(40));
        result.optimized_experience.forEach((item, i) => {
          lines.push(`[${i + 1}] BEFORE: ${item.original}`);
          lines.push(`    AFTER:  ${item.optimized}`);
          if (item.reason) lines.push(`    WHY:   ${item.reason}`);
          if (item.ats_improvement) lines.push(`    ATS:   ${item.ats_improvement}`);
          lines.push('');
        });
      }

      if (result.optimized_projects?.length > 0) {
        lines.push('PROJECT IMPROVEMENTS');
        lines.push('-'.repeat(40));
        result.optimized_projects.forEach((item, i) => {
          lines.push(`[${i + 1}] BEFORE: ${item.original}`);
          lines.push(`    AFTER:  ${item.optimized}`);
          if (item.reason) lines.push(`    WHY:   ${item.reason}`);
          lines.push('');
        });
      }

      if (result.optimized_skills?.optimized_order?.length > 0) {
        lines.push('SKILLS (REORDERED FOR THIS JOB)');
        lines.push('-'.repeat(40));
        lines.push(result.optimized_skills.optimized_order.join(', '));
        if (result.optimized_skills.reasoning) {
          lines.push(`Reasoning: ${result.optimized_skills.reasoning}`);
        }
        lines.push('');
      }

      if (result.keyword_additions?.length > 0) {
        lines.push('KEYWORDS TO ADD');
        lines.push('-'.repeat(40));
        result.keyword_additions.forEach((k) => {
          lines.push(`+ ${k.keyword} → Add to: ${k.where_added}`);
          if (k.reason) lines.push(`  Reason: ${k.reason}`);
        });
        lines.push('');
      }

      lines.push('OPTIMIZATION SCORES');
      lines.push('-'.repeat(40));
      lines.push(`Overall Optimization Score: ${result.optimization_score}/100`);
      lines.push(`Estimated ATS Improvement:  +${result.estimated_ats_improvement}%`);
      lines.push(`Estimated Job Match Boost:  +${result.estimated_match_increase}%`);
      lines.push(`Interview Callback Boost:   +${result.estimated_interview_probability}%`);

      const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `optimized_resume_${(selectedJob?.company_name ?? 'job').replace(/\s+/g, '_')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Resume Optimizer</h1>
        <p className="mt-2 text-muted-foreground">
          AI rewrites your resume bullets and summary to maximize ATS score and job match
        </p>
      </div>

      {/* Selector panel */}
      <div className="bg-card rounded-xl p-6 border space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="text-sm font-medium mb-1.5 block">Your Resume</label>
            {resumes.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                <a href="/resume" className="text-primary underline">Upload a resume</a> first.
              </p>
            ) : (
              <select
                value={selectedResumeId}
                onChange={(e) => setSelectedResumeId(e.target.value)}
                className="w-full px-3 py-2.5 border rounded-lg bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="">— select resume —</option>
                {resumes.map((r) => (
                  <option key={r.id} value={r.id}>{r.original_filename}</option>
                ))}
              </select>
            )}
          </div>
          <div>
            <label className="text-sm font-medium mb-1.5 block">Target Job</label>
            {jobs.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                <a href="/job-analysis" className="text-primary underline">Analyze a job</a> first.
              </p>
            ) : (
              <select
                value={selectedJobId}
                onChange={(e) => setSelectedJobId(e.target.value)}
                className="w-full px-3 py-2.5 border rounded-lg bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="">— select job —</option>
                {jobs.map((j) => (
                  <option key={j.id} value={j.id}>{j.title} @ {j.company_name}</option>
                ))}
              </select>
            )}
          </div>
        </div>

        {error && (
          <div className="flex items-start gap-2 text-sm text-destructive bg-destructive/10 px-3 py-2 rounded-lg">
            <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
            {error}
          </div>
        )}

        <button
          onClick={handleOptimize}
          disabled={optimizing || !selectedResumeId || !selectedJobId}
          className="w-full py-3 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 disabled:opacity-50 flex items-center justify-center gap-2 transition-colors"
        >
          {optimizing ? (
            <><Loader2 className="w-4 h-4 animate-spin" /> AI is optimizing your resume...</>
          ) : (
            <><Sparkles className="w-4 h-4" /> Optimize Resume</>
          )}
        </button>
      </div>

      {/* Empty state */}
      {!result && !optimizing && (
        <div className="text-center py-16 bg-card rounded-xl border">
          <Sparkles className="w-10 h-10 mx-auto text-muted-foreground opacity-30 mb-3" />
          <p className="text-muted-foreground text-sm max-w-sm mx-auto">
            {resumes.length === 0
              ? 'Upload your resume first, then come back to optimize it for any job.'
              : jobs.length === 0
              ? 'Analyze a job description first on the Job Analysis page, then optimize your resume for it.'
              : 'Select your resume and target job above, then click Optimize.'}
          </p>
        </div>
      )}

      {/* Results */}
      {result && (
        <div className="space-y-6">

          {/* Score cards */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <ScoreRing value={`${result.optimization_score}/100` as any} label="Optimization Score" color="text-primary" />
            <ScoreRing value={`+${result.estimated_ats_improvement}%` as any} label="ATS Improvement" color="text-green-600 dark:text-green-400" />
            <ScoreRing value={`+${result.estimated_match_increase}%` as any} label="Match Boost" color="text-blue-600 dark:text-blue-400" />
            <ScoreRing value={`+${result.estimated_interview_probability}%` as any} label="Interview Boost" color="text-purple-600 dark:text-purple-400" />
          </div>

          {/* Optimized Summary */}
          {result.optimized_summary && (
            <div className="bg-card rounded-xl p-6 border">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" /> Optimized Professional Summary
              </h3>
              <div className="p-4 bg-green-50 dark:bg-green-950/40 border border-green-200 dark:border-green-800 rounded-lg">
                <p className="text-sm leading-relaxed">{result.optimized_summary}</p>
              </div>
            </div>
          )}

          {/* Experience Changes */}
          {result.optimized_experience?.length > 0 && (
            <div className="bg-card rounded-xl p-6 border">
              <h3 className="font-semibold mb-4">
                Experience Improvements <span className="text-muted-foreground font-normal text-sm">({result.optimized_experience.length} bullets)</span>
              </h3>
              <div className="space-y-3">
                {result.optimized_experience.map((item, i) => (
                  <div key={i} className="border rounded-lg overflow-hidden">
                    <div className="p-3 bg-red-50/50 dark:bg-red-950/30 border-b flex gap-2">
                      <span className="text-xs font-semibold text-red-500 uppercase shrink-0 mt-0.5">Before</span>
                      <p className="text-sm text-muted-foreground">{item.original}</p>
                    </div>
                    <div className="p-3 bg-green-50/50 dark:bg-green-950/30">
                      <div className="flex gap-2 mb-1">
                        <span className="text-xs font-semibold text-green-500 uppercase shrink-0 mt-0.5">After</span>
                        <p className="text-sm font-medium">{item.optimized}</p>
                      </div>
                      {(item.reason || item.ats_improvement) && (
                        <p className="text-xs text-muted-foreground pl-8">
                          💡 {item.reason}{item.ats_improvement ? ` · ATS: ${item.ats_improvement}` : ''}
                        </p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Project Changes */}
          {result.optimized_projects?.length > 0 && (
            <div className="bg-card rounded-xl p-6 border">
              <h3 className="font-semibold mb-4">
                Project Improvements <span className="text-muted-foreground font-normal text-sm">({result.optimized_projects.length} projects)</span>
              </h3>
              <div className="space-y-3">
                {result.optimized_projects.map((item, i) => (
                  <div key={i} className="border rounded-lg overflow-hidden">
                    <div className="p-3 bg-red-50/50 dark:bg-red-950/30 border-b flex gap-2">
                      <span className="text-xs font-semibold text-red-500 uppercase shrink-0 mt-0.5">Before</span>
                      <p className="text-sm text-muted-foreground">{item.original}</p>
                    </div>
                    <div className="p-3 bg-green-50/50 dark:bg-green-950/30">
                      <div className="flex gap-2 mb-1">
                        <span className="text-xs font-semibold text-green-500 uppercase shrink-0 mt-0.5">After</span>
                        <p className="text-sm font-medium">{item.optimized}</p>
                      </div>
                      {item.reason && (
                        <p className="text-xs text-muted-foreground pl-8">💡 {item.reason}</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Skills reorder */}
          {result.optimized_skills?.optimized_order?.length > 0 && (
            <div className="bg-card rounded-xl p-6 border">
              <h3 className="font-semibold mb-4">Skills Reordered for This Job</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-muted-foreground font-medium mb-2 uppercase tracking-wide">Original Order</p>
                  <div className="flex flex-wrap gap-1.5">
                    {result.optimized_skills.original_order.slice(0, 12).map((s, i) => (
                      <span key={i} className="px-2.5 py-1 text-xs bg-secondary rounded-full text-muted-foreground">{s}</span>
                    ))}
                  </div>
                </div>
                <div>
                  <p className="text-xs text-green-600 font-medium mb-2 uppercase tracking-wide">Optimized Order ✓</p>
                  <div className="flex flex-wrap gap-1.5">
                    {result.optimized_skills.optimized_order.slice(0, 12).map((s, i) => (
                      <span key={i} className={`px-2.5 py-1 text-xs rounded-full ${i < 5 ? 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 font-medium' : 'bg-secondary'}`}>{s}</span>
                    ))}
                  </div>
                </div>
              </div>
              {result.optimized_skills.reasoning && (
                <p className="text-xs text-muted-foreground mt-3 pt-3 border-t">💡 {result.optimized_skills.reasoning}</p>
              )}
            </div>
          )}

          {/* Keywords */}
          {result.keyword_additions?.length > 0 && (
            <div className="bg-card rounded-xl p-6 border">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                Keywords to Add for ATS <span className="text-muted-foreground font-normal text-sm">({result.keyword_additions.length} keywords)</span>
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {result.keyword_additions.map((k, i) => (
                  <div key={i} className="flex items-start gap-2 p-3 bg-secondary/50 rounded-lg">
                    <span className="px-2 py-0.5 text-xs font-semibold bg-primary text-primary-foreground rounded shrink-0">{k.keyword}</span>
                    <div className="text-xs">
                      <span className="text-muted-foreground">Add to </span>
                      <span className="font-medium">{k.where_added}</span>
                      {k.reason && <p className="text-muted-foreground mt-0.5">{k.reason}</p>}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Action buttons */}
          <div className="flex gap-3">
            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex-1 py-3 bg-primary text-primary-foreground rounded-lg font-medium flex items-center justify-center gap-2 hover:bg-primary/90 transition-colors disabled:opacity-50"
            >
              {downloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              Download Optimized Resume
            </button>
            <button
              onClick={handleOptimize}
              disabled={optimizing}
              className="px-6 py-3 border rounded-lg text-sm flex items-center gap-2 hover:bg-secondary transition-colors disabled:opacity-50"
            >
              <RefreshCw className="w-4 h-4" /> Re-optimize
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
